layout_spectrum: 0.1006127
color:
  saturation: 0.1799632
  brandStrength: 0.6924757
  lightness: 0.78255
  brandColors:
    - '#FBFBFF'
    - '#38311F'
    - '#864C98'
    - '#A5B3F3'
    - '#212B72'
  rhythmicContrast: 0.3052184
typography_spectrum: 0.06904245
name: NextGen_Wales
